name: "Multisynq Synchronizer"
description: "Run a Multisynq Synchronizer through your Home Assistant instance to participate in DePIN networks and earn rewards"
version: "1.1.2"
slug: "multisynq_synchronizer"
init: false
arch:
  - aarch64
  - amd64
url: "https://github.com/multisynq/synchronizer-ha"
# image: "ghcr.io/multisynq/{arch}-synchronizer-ha"  # Commented out for local builds
options:
  synq_key: null
  wallet_address: null
schema:
  synq_key: str
  wallet_address: str
ports:
  "3333/tcp": 3333
  "9090/tcp": 9090
map:
  - "share:rw"
