name: "Multisynq Synchronizer"
description: "Run a Multisynq Synchronizer through your Home Assistant instance"
version: "1.0.0"
slug: "multisynq_synchronizer"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
url: "https://github.com/multisynq/synchronizer-ha"
maintainer: "Miguel Matos <miguel.matos@multisynq.io>"
options:
  synq_key: ""
  wallet_address: ""
  sync_name: "Home Assistant Sync"
  auto_start: true
  web_dashboard:
    enable: true
    port: 3000
    metrics_port: 3001
    password: ""
  advanced:
    log_level: "info"
schema:
  synq_key: str
  wallet_address: str
  sync_name: str?
  auto_start: bool?
  web_dashboard:
    enable: bool?
    port: int(1024,65535)?
    metrics_port: int(1024,65535)?
    password: password?
  advanced:
    log_level: list(debug|info|warning|error)?
ports:
  3000/tcp: 3000
  3001/tcp: 3001
ports_description:
  3000/tcp: "Web Dashboard"
  3001/tcp: "Metrics API"
# host_network: false
