name: "Multisynq Synchronizer"
description: "Run a Multisynq Synchronizer through your Home Assistant instance to participate in DePIN networks and earn rewards"
version: "1.0.3"
slug: "multisynq_synchronizer"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
url: "https://github.com/multisynq/synchronizer-ha"
documentation: "https://github.com/multisynq/synchronizer-cli"
maintainer: "Miguel Matos <miguel.matos@multisynq.io>"
options:
  synq_key: ""
  wallet_address: ""
  sync_name: "Home Assistant Sync"
schema:
  synq_key: str
  wallet_address: str
  sync_name: str?
ports:
  3000/tcp: 3000
  3001/tcp: 3001
ports_description:
  3000/tcp: "Web Dashboard"
  3001/tcp: "Metrics API"
startup: services
