name: "Multisynq Synchronizer"
description: "Run a Multisynq Synchronizer through your Home Assistant instance to participate in DePIN networks and earn rewards"
version: "1.1.1"
slug: "multisynq_synchronizer"
init: false
arch:
  - aarch64
  - amd64
url: "https://github.com/multisynq/synchronizer-ha"
documentation: "https://github.com/multisynq/synchronizer-cli"
maintainer: "Miguel Matos <miguel.matos@multisynq.io>"
host_network: false
advanced: false
stage: stable
startup: application
boot: auto
image: "ghcr.io/multisynq/synchronizer-ha/multisynq_synchronizer"
options:
  synq_key: ""
  wallet_address: ""
  sync_name: "Home Assistant Synchronizer"
schema:
  synq_key: str
  wallet_address: str
  sync_name: str?
ports:
  "3333/tcp": 3333
  "9090/tcp": 9090
map:
  - "share:rw"
